# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provider "virtualbox" do |vb1|
	vb1.name = "TestVagrantVM"
	vb1.gui = false
	vb1.memory = "2048"
	vb1.cpus = 1
  end

config.vm.hostname = "VagrantVM"
config.vm.synced_folder ".", "/home/vagrant/code",
	owner: "www-data", group: "www-data"
config.vm.provision "shell", path: "provision.sh"
end
