- name: Copy wp-config.php
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: '{{ wordpress_www_folder }}/wp-config.php'
    owner: '{{ wordpress_www_user }}'

- name: Copy ports.conf
  ansible.builtin.template:
    src: ports.conf.j2
    dest: '/etc/apache2/ports.conf'
    owner: '{{ wordpress_www_user }}'
