version: "3"

services:

  centos:
    build: ./centos
    ports:
      - "8085:80"
    volumes:
      - ./WebPage:/usr/share/nginx/html
    container_name: my-centos-7
    networks:
      - my_net
    restart: always

  ubuntu-20.04:
    build: ./ubuntu_20.04
    ports:
      - "8086:80"
    volumes:
      - ./WebPage:/var/www/html
    container_name: my-ubuntu-20.04
    networks:
      - my_net
    restart: always

  ubuntu-22.04:
    build: ./ubuntu_22.04
    ports:
      - "8087:80"
    volumes:
      - ./WebPage:/var/www/html
    container_name: my-ubuntu-22.04
    networks:
      - other_net
    restart: always

networks:
  my_net:
  other_net:
