---
- name: Install HTTPD on the CentOS system
  hosts: CentOS_servers
  become: yes

  vars:
    source: ./WebPage/index.html
    destin: /var/www/html

  tasks:
  - name: Setting yum
    shell: "cd /etc/yum.repos.d/ | sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* | sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*"

  - name: Install Apache Web_Server on the CentOS
    yum: name=httpd state=latest

  - name: Copy Page to the CentOS servers
    copy: src={{ source }} dest={{ destin}} mode=0555
    notify: Restart Apache
  
  - name: Start and Enable Apache Web_server on the CentOS
    service: name=httpd state=started enabled=yes

  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted

- name: Install HTTPD on the Debian/Ubuntu system
  hosts: Debian_distr_family
  become: yes

  vars:
    source: ./WebPage/index.html
    destin: /var/www/html

  tasks:
  - name: Install Apache Web_Server on the Debian/Ubuntu system
    apt: name=apache2 state=latest

  - name: Copy Page to the Debian/Ubuntu servers
    copy: src={{ source }} dest={{ destin}} mode=0555
    notify: Restart Apache

  - name: Start and Enable Apache Web_server on the Debian/Ubuntu system
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
...

