---
- name: Install HTTPD and Copy Web Page
  hosts: Staging_servers
  become: yes

  vars:
    source: ./WebPage/index.html
    destin: /var/www/html

  tasks:
  - name: Print OS version
    debug: var=ansible_os_family

  # OS RedHat_family

  - block:

    - name: Install Apache Web_Server on the RedHat
      yum: name=httpd state=latest

    - name: Copy Page to the RedHat servers
      copy: src={{ source }} dest={{ destin}} mode=0555
      notify: Restart Apache RedHat

    - name: Start and Enable Apache Web_server on the RedHat
      service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  # OS Debian_family

  - block:

    - name: Install Apache Web_Server on the Debian/Ubuntu system
      apt: name=apache2 state=latest

    - name: Copy Page to the Debian/Ubuntu servers
      copy: src={{ source }} dest={{ destin}} mode=0555
      notify: Restart Apache Debian

    - name: Start and Enable Apache Web_server on the Debian/Ubuntu system
      service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted

  - name: Restart Apache Debian
    service: name=apache2 state=restarted
...
