# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "UbuntuVM" do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-20.04"
    ubuntu.vm.box_check_update = false
    ubuntu.vm.synced_folder ".", "/vagrant"
    ubuntu.vm.provider "virtualbox" do |vb1|
      vb1.name = "UbuntuVM"
      vb1.gui = false
      vb1.memory = "1024"
      vb1.cpus = 1
    end
    ubuntu.vm.hostname = "UBVM"
    ubuntu.vm.network "public_network"
    ubuntu.vm.provision "shell", path: "provApacheU.sh"
    ubuntu.ssh.username = "vagrant"
    ubuntu.ssh.password = "vagrant"
  end

  config.vm.define "CentOSVM" do |centOS|
    centOS.vm.box = "D:/DevOps courses (TeachMeSkills)/Class 4/Homework/CentoSbox"
    centOS.vm.box_check_update = false
    centOS.vm.synced_folder ".", "/vagrant"
    centOS.vm.provider "virtualbox" do |vb2|
      vb2.name = "CentOSVM"
      vb2.gui = false
      vb2.memory = "1024"
      vb2.cpus = 1
    end
    centOS.vm.hostname = "CenVM"
    centOS.vm.network "public_network"
    centOS.vm.provision "shell", inline: "
            yum update -y
            yum install httpd -y
            systemctl start httpd && systemctl enable httpd
            "
    
  end
    
end
