apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  USER_NAME: bG9kaXNfYXY=
  PASSWORD: aHdfbGVzc29uNDg=
  GROUP: RE9TMTEtb25s
  ENVIRONMENT: S3ViZXJuZXRlcyAoSzhzKQ==
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: secret-test
      image: ubuntu:20.04
      envFrom:
      - secretRef:
          name: mysecret
  restartPolicy: Never
