{
 "title": "my tms dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ui_request / ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ui_request_count{http_status=\"200\", instance=\"ui.default.svc.cluster.local:9292\", job=\"reddit\", method=\"GET\", path=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ui_request / post",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ui_request_count{http_status=\"303\", instance=\"ui.default.svc.cluster.local:9292\", job=\"reddit\", method=\"POST\", path=\"/new\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ui_request / metrics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ui_request_count{http_status=\"200\", instance=\"ui.default.svc.cluster.local:9292\", job=\"reddit\", method=\"GET\", path=\"/metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}