apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      imagePullSecrets:
      - name: ${GITHUB_REGISTRY_SECRET}
      containers:
      - name: ui
        image: ${REGISTRY}/ui:${RELEASE_VER}
        envFrom:
          - configMapRef:
              name: ui
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 9292
