apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "$DOCKER_HOST_IP"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
  podSubnet: "$POD_SUBNET"
  serviceSubnet: "$SERVICE_SUBNET"
  disableDefaultCNI: true # disable kindnet
nodes:
- role: control-plane
- role: worker
  labels:
    type: worker
    nodePort: true
    ingress-ready: true
  extraMounts:
    - hostPath: "$VOLUME_NODE1_HOST"
      containerPath: "$VOLUME_NODE1_CONTAINER"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 30103
    hostPort: 30103
    protocol: tcp # Optional, defaults to tcp
- role: worker
  labels:
    type: worker
    nodePort: false
  extraMounts:
    - hostPath: "$VOLUME_NODE2_HOST"
      containerPath: "$VOLUME_NODE2_CONTAINER"
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP
