version: "3"

services:

  centos:
    build: ./centos
    depends_on:
      - "ubuntu-20.04"
      - "ubuntu-22.04"
    image: nginx:centos 
    ports:
      - "8085:80"
      - "44301:443"
    volumes:
      - ./WebPage/centos_page:/opt/nginx/html      
      - ./centos/nginx_logs:/opt/nginx/logs
    container_name: my-centos-7
    links:
      - "ubuntu-20.04"
      - "ubuntu-22.04"
    networks:
      - my_net
    extra_hosts:
      - "my-domain:192.168.1.240"
    restart: always

  ubuntu-20.04:
    build: ./ubuntu_20.04
    image: apache2:ub20
    ports:
      - "8086:80"
      - "44300:443"
    volumes:
      - ./WebPage/ub20_page:/opt/apache2/html
      - ./ubuntu_20.04/apache2_logs:/opt/apache2/logs
    container_name: my-ubuntu-20.04
    networks:
      - my_net
    extra_hosts:
      - "my-domain:192.168.1.240"
    restart: always

  ubuntu-22.04:
    build: ./ubuntu_22.04
    image: apache2:ub22
    ports:
      - "8087:80"
      - "44302:443"
    volumes:
      - ./WebPage/ub22_page:/opt/apache2/html
      - ./ubuntu_22.04/apache2_logs:/opt/apache2/logs
    container_name: my-ubuntu-22.04
    networks:
      - my_net
    extra_hosts:
      - "my-domain:192.168.1.240"
    restart: always

  haproxy:
    build: ./haproxy
    depends_on:
      - "ubuntu-20.04"
      - "ubuntu-22.04"
      - "centos"
    image: haproxy:round
    ports:
      - "8081:80"
    container_name: my-haproxy
    links:
      - "centos"
      - "ubuntu-20.04"
      - "ubuntu-22.04"
    networks:
      - my_net
    extra_hosts:
      - "my-domain:192.168.1.240"
    restart: always

networks:
  my_net:  
