apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: httpd
spec:
  serviceName: "httpd"
  selector:
    matchLabels:
      app: httpd
  replicas: 4
  template:
    metadata:
      labels:
        app: httpd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: httpd
        image: httpd:2.2
        ports:
        - containerPort: 80
          name: httpd
---
