apiVersion: v1
kind: Pod
metadata:
  name: "apache"
  namespace: default
  labels:
    app: "apache"
spec:
  containers:
  - name: apache
    image: ubuntu/apache2
    env:
    - name: KEY
      valueFrom:
        configMapKeyRef:
          name: myconfig
          key: key_name
    ports:
    - containerPort: 80
      name:  http
    volumeMounts:
    - name: config
      mountPath: /etc/apache2/sites-available/000-default.conf
      subPath: default.conf
    - name: config
      mountPath: /var/www/html/index.html
      subPath: index.html
  volumes:
    - name: config
      configMap:
        name: myconfig
        items:
          - key: apache.conf
            path: default.conf
          - key: index.html
            path: index.html
  restartPolicy: Always
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: myconfig
  namespace: default
data:
  key_name: LA
  apache.conf: |
    <VirtualHost *:80>
        
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        
    </VirtualHost>
  index.html: |
    <h1>This is my page. Owner by Lodis Artyom</h1>
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: default
spec:
  selector:
    app: apache
  type: NodePort
  ports:
  - name: apache
    protocol: TCP
    port: 8080
    targetPort: 80    
    nodePort: 30103
