apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mystorage
  hostPath:
    path: /var/local/page
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: apache
spec:
  selector:
    matchLabels:
      name: apache
  template:
    metadata:
      labels:
        name: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4        
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs
          name: apache-pv
      volumes:
      - name: apache-pv
        persistentVolumeClaim:       
          claimName: mypvc              
      nodeSelector:
        nodePort: "false"
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: default
  labels:
    app: mypvc
spec:
  storageClassName: mystorage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: default
spec:
  selector:
    app: apache
  type: NodePort
  ports:
  - name: apache
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30103
